"""initial schema

Revision ID: 08f0c5e09e32
Revises:
Create Date: 2026-08-17 18:34:10.571347

"""

import os
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# ── seed ──────────────────────────────────────────────────────────────────────
#
# Seeded in the migration rather than a script so that every database — local, test,
# demo, production — starts with the same taxonomy and the same owner row. A
# separately-run seed step is one someone forgets.

#: (parent, name, kind). A parent of None makes it a top-level category.
_CATEGORIES: list[tuple[str | None, str, str]] = [
    (None, "Income", "income"),
    ("Income", "Salary", "income"),
    ("Income", "Interest", "income"),
    ("Income", "Dividends", "income"),
    ("Income", "Other Income", "income"),
    (None, "Housing", "expense"),
    ("Housing", "Rent or Mortgage", "expense"),
    ("Housing", "Utilities", "expense"),
    ("Housing", "Home Maintenance", "expense"),
    (None, "Food", "expense"),
    ("Food", "Groceries", "expense"),
    ("Food", "Restaurants", "expense"),
    (None, "Transport", "expense"),
    ("Transport", "Fuel", "expense"),
    ("Transport", "Rideshare and Transit", "expense"),
    ("Transport", "Car Maintenance", "expense"),
    (None, "Health", "expense"),
    ("Health", "Medical", "expense"),
    ("Health", "Pharmacy", "expense"),
    (None, "Personal", "expense"),
    ("Personal", "Shopping", "expense"),
    ("Personal", "Entertainment", "expense"),
    ("Personal", "Subscriptions", "expense"),
    ("Personal", "Travel", "expense"),
    (None, "Financial", "expense"),
    ("Financial", "Fees", "expense"),
    ("Financial", "Taxes", "expense"),
    ("Financial", "Insurance", "expense"),
    (None, "Uncategorised", "expense"),
    # Transfers are not spending. Excluding them is what makes every number on the
    # dashboard believable — see docs/ARCHITECTURE.md#data-model.
    (None, "Transfer", "transfer"),
    ("Transfer", "Credit Card Payment", "transfer"),
    ("Transfer", "Investment Contribution", "transfer"),
]


def _seed() -> None:
    bind = op.get_bind()

    # The household's first user. The users table is also the auth allowlist, so this
    # is the only place an identity is declared.
    bind.execute(
        sa.text("INSERT INTO users (email, display_name, is_active) VALUES (:email, :name, true)"),
        {
            "email": os.environ.get("OWNER_EMAIL", "owner@example.invalid"),
            "name": os.environ.get("OWNER_DISPLAY_NAME", "Owner"),
        },
    )

    # Declares this database as synthetic. The seed generator (018) refuses to run
    # when is_real is true, which is what would catch a mistyped connection string
    # before it overwrote a real financial history.
    bind.execute(
        sa.text("INSERT INTO data_marker (is_real, note) VALUES (false, :note)"),
        {"note": "Set is_real=true on the production database after first deploy."},
    )

    parents: dict[str, int] = {}
    for parent, name, kind in _CATEGORIES:
        parent_id = parents[parent] if parent else None
        row = bind.execute(
            sa.text(
                "INSERT INTO categories (parent_id, name, kind) "
                "VALUES (:parent_id, :name, :kind) RETURNING id"
            ),
            {"parent_id": parent_id, "name": name, "kind": kind},
        ).one()
        if parent is None:
            parents[name] = row[0]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("parent_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column(
            "kind", sa.Enum("income", "expense", "transfer", name="category_kind"), nullable=False
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["categories.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("parent_id", "name", name="uq_category_parent_name"),
    )
    op.create_index(op.f("ix_categories_kind"), "categories", ["kind"], unique=False)
    op.create_index(op.f("ix_categories_parent_id"), "categories", ["parent_id"], unique=False)
    op.create_table(
        "data_marker",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("is_real", sa.Boolean(), nullable=False),
        sa.Column("note", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "institutions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("display_name", sa.String(length=120), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "accounts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("institution_id", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column(
            "kind",
            sa.Enum("liquid_asset", "illiquid_asset", "liability", name="account_kind"),
            nullable=False,
        ),
        sa.Column(
            "subtype",
            sa.Enum(
                "checking",
                "savings",
                "money_market",
                "cd",
                "brokerage",
                "ira",
                "roth_ira",
                "401k",
                "hsa",
                "529",
                "real_estate",
                "vehicle",
                "other_asset",
                "credit_card",
                "mortgage",
                "auto_loan",
                "student_loan",
                "personal_loan",
                "other_liability",
                name="account_subtype",
            ),
            nullable=False,
        ),
        sa.Column(
            "source",
            sa.Enum("manual", "csv", "teller", "plaid", "simplefin", name="data_source"),
            nullable=False,
        ),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("closed_at", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("currency = 'USD'", name="ck_accounts_currency_usd"),
        sa.ForeignKeyConstraint(["institution_id"], ["institutions.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_accounts_institution_id"), "accounts", ["institution_id"], unique=False
    )
    op.create_index(op.f("ix_accounts_kind"), "accounts", ["kind"], unique=False)
    op.create_table(
        "categorization_rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("pattern", sa.String(length=255), nullable=False),
        sa.Column(
            "match_type",
            sa.Enum("contains", "equals", "starts_with", "regex", name="match_type"),
            nullable=False,
        ),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rules_priority", "categorization_rules", ["priority"], unique=False)
    op.create_table(
        "credentials",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("credential_id", sa.LargeBinary(), nullable=False),
        sa.Column("public_key", sa.LargeBinary(), nullable=False),
        sa.Column("sign_count", sa.BigInteger(), nullable=False),
        sa.Column("transports", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("credential_id"),
    )
    op.create_index(op.f("ix_credentials_user_id"), "credentials", ["user_id"], unique=False)
    op.create_table(
        "balance_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("as_of", sa.Date(), nullable=False),
        sa.Column("balance", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column(
            "source",
            sa.Enum("manual", "csv", "teller", "plaid", "simplefin", name="data_source"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "as_of", name="uq_snapshot_account_date"),
    )
    op.create_index(
        "ix_snapshots_account_as_of", "balance_snapshots", ["account_id", "as_of"], unique=False
    )
    op.create_table(
        "import_mappings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("column_map", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("account_id", "name", name="uq_mapping_account_name"),
    )
    op.create_index(
        op.f("ix_import_mappings_account_id"), "import_mappings", ["account_id"], unique=False
    )
    op.create_table(
        "ownership_stakes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("owner_user_id", sa.Integer(), nullable=False),
        sa.Column("percentage", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("effective_to", sa.Date(), nullable=True),
        sa.CheckConstraint(
            "effective_to IS NULL OR effective_to > effective_from", name="ck_stakes_date_order"
        ),
        sa.CheckConstraint(
            "percentage > 0 AND percentage <= 100", name="ck_stakes_percentage_range"
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["owner_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ownership_stakes_owner_user_id"),
        "ownership_stakes",
        ["owner_user_id"],
        unique=False,
    )
    op.create_index(
        "ix_stakes_account_effective",
        "ownership_stakes",
        ["account_id", "effective_from"],
        unique=False,
    )
    op.create_table(
        "transactions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("account_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=255), nullable=True),
        sa.Column("posted_at", sa.Date(), nullable=False),
        sa.Column("amount", sa.Numeric(precision=19, scale=2), nullable=False),
        sa.Column("merchant", sa.String(length=255), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("category_id", sa.Integer(), nullable=True),
        sa.Column(
            "category_source",
            sa.Enum("import", "rule", "manual", name="category_source"),
            nullable=True,
        ),
        sa.Column("transfer_group_id", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["account_id"], ["accounts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_transactions_account_posted", "transactions", ["account_id", "posted_at"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_category_id"), "transactions", ["category_id"], unique=False
    )
    op.create_index(op.f("ix_transactions_merchant"), "transactions", ["merchant"], unique=False)
    op.create_index("ix_transactions_posted_at", "transactions", ["posted_at"], unique=False)
    op.create_index(
        op.f("ix_transactions_transfer_group_id"),
        "transactions",
        ["transfer_group_id"],
        unique=False,
    )
    op.create_index(
        "uq_transaction_account_external",
        "transactions",
        ["account_id", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    # ### end Alembic commands ###

    _seed()


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq_transaction_account_external",
        table_name="transactions",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_transactions_transfer_group_id"), table_name="transactions")
    op.drop_index("ix_transactions_posted_at", table_name="transactions")
    op.drop_index(op.f("ix_transactions_merchant"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_category_id"), table_name="transactions")
    op.drop_index("ix_transactions_account_posted", table_name="transactions")
    op.drop_table("transactions")
    op.drop_index("ix_stakes_account_effective", table_name="ownership_stakes")
    op.drop_index(op.f("ix_ownership_stakes_owner_user_id"), table_name="ownership_stakes")
    op.drop_table("ownership_stakes")
    op.drop_index(op.f("ix_import_mappings_account_id"), table_name="import_mappings")
    op.drop_table("import_mappings")
    op.drop_index("ix_snapshots_account_as_of", table_name="balance_snapshots")
    op.drop_table("balance_snapshots")
    op.drop_index(op.f("ix_credentials_user_id"), table_name="credentials")
    op.drop_table("credentials")
    op.drop_index("ix_rules_priority", table_name="categorization_rules")
    op.drop_table("categorization_rules")
    op.drop_index(op.f("ix_accounts_kind"), table_name="accounts")
    op.drop_index(op.f("ix_accounts_institution_id"), table_name="accounts")
    op.drop_table("accounts")
    op.drop_table("users")
    op.drop_table("institutions")
    op.drop_table("data_marker")
    op.drop_index(op.f("ix_categories_parent_id"), table_name="categories")
    op.drop_index(op.f("ix_categories_kind"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
    # Tables are gone but their enum types are not — Postgres keeps a type until it
    # is dropped explicitly. Leaving them behind makes `downgrade` followed by
    # `upgrade` fail with "type already exists", which is exactly the round trip the
    # schema test exercises.
    for enum_name in (
        "category_source",
        "category_kind",
        "match_type",
        "data_source",
        "account_subtype",
        "account_kind",
    ):
        op.execute(f"DROP TYPE IF EXISTS {enum_name}")
