/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/accounts": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List All
     * @description Accounts grouped by kind, with raw and ownership-adjusted subtotals.
     *
     *     Both values are exposed deliberately. A 50%-owned rental should visibly show the
     *     full property value and your share — that distinction is the feature, and showing
     *     only one of them throws it away.
     */
    get: operations["list_all_accounts_get"];
    put?: never;
    /**
     * Create
     * @description Create an account, its explicit 100% stake, and any opening balance.
     *
     *     All in one transaction. An account with no stake row contributes to no net worth
     *     figure, so a partial success would create something that exists and is
     *     simultaneously invisible.
     */
    post: operations["create_accounts_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/{account_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Detail */
    get: operations["detail_accounts__account_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update
     * @description Rename, re-file, or close an account.
     *
     *     Closing is a date, not a deletion: the history stays intact and net worth simply
     *     stops counting it from that day — see docs/ARCHITECTURE.md#data-model.
     */
    patch: operations["update_accounts__account_id__patch"];
    trace?: never;
  };
  "/accounts/{account_id}/balances": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Add Balance
     * @description Record a snapshot. Re-recording the same date replaces the value.
     */
    post: operations["add_balance_accounts__account_id__balances_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/{account_id}/history": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** History */
    get: operations["history_accounts__account_id__history_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/accounts/{account_id}/stakes": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Set Stake
     * @description Close the stake in force and open a new one, atomically.
     *
     *     Historical net worth is untouched: the old row is closed on the new row's start
     *     date rather than edited, so every figure before that date still reads the old
     *     percentage.
     */
    post: operations["set_stake_accounts__account_id__stakes_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authentication Options */
    post: operations["authentication_options_auth_login_options_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/login/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Authentication Verify */
    post: operations["authentication_verify_auth_login_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register/options": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Registration Options */
    post: operations["registration_options_auth_register_options_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/register/verify": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Registration Verify */
    post: operations["registration_verify_auth_register_verify_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/auth/session": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Session */
    get: operations["read_session_auth_session_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/categories": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Categories
     * @description Every category, parents before their own children.
     *
     *     Ordered by `(parent_id, name)` with parents first, so a client can build a grouped
     *     picker by walking the list once rather than sorting a tree it has to rebuild.
     */
    get: operations["list_categories_categories_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/export": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Export
     * @description Every row, as JSON.
     *
     *     Deliberately the whole dataset rather than a filtered view: the point is that
     *     nothing is trapped in here. Ownership stakes and their effective dates come too,
     *     because without them the balances alone cannot reconstruct a net worth figure.
     */
    get: operations["get_export_export_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Health
     * @description Liveness: the process is up and serving.
     *
     *     Touches no database, by design. Fly probes this endpoint, and a check that fails
     *     on a transient database blip would have the platform restart instances that are
     *     perfectly healthy — turning a brief database problem into an outage.
     */
    get: operations["health_health_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/import/csv/commit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Commit Csv
     * @description Idempotent upsert. Re-importing the same file changes nothing.
     */
    post: operations["commit_csv_import_csv_commit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/import/csv/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Csv
     * @description Dry run. Writes nothing — the safety net for importing real exports.
     *
     *     `mapping` is an optional JSON `ColumnMapping`. Without it the account's saved
     *     mapping is used, falling back to detection from the header row — so the first look
     *     at a file needs no configuration. With it, a reader who spotted a wrong column or
     *     an inverted sign can see the corrected result before committing to it, which is
     *     the difference between a preview and a promise.
     *
     *     It arrives as a JSON string because the rest of the request is multipart: a file
     *     upload cannot also carry a JSON body.
     */
    post: operations["preview_csv_import_csv_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/net-worth": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Net Worth
     * @description Net worth on a date, defaulting to today.
     *
     *     Accounts are excluded — never counted as zero — when they had no snapshot by
     *     `as_of`, when they closed on or before it, or when the viewer holds no stake in
     *     them. `stale_account_ids` names the accounts whose balance was carried forward
     *     past the 90-day cap; they are still included, because dropping them would make net
     *     worth silently fall on the day a snapshot aged out.
     */
    get: operations["get_net_worth_net_worth_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/net-worth/series": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Net Worth Series
     * @description Net worth at each point in a range.
     *
     *     **Carry-forward.** Each point uses the latest snapshot at or before that date, per
     *     account — matching `balances.balance_in_force`. Nobody records every account every
     *     day, so without this a chart would be mostly holes. Carry-forward is capped at 90
     *     days; past that the balance is still used but the point reports it via
     *     `stale_account_count`, so a flat stretch built from a year-old number is
     *     distinguishable from an observed one.
     *
     *     **Each point is independent**, computed with that date's balances *and* that
     *     date's ownership stakes. A stake that changes in June does not rewrite May.
     *
     *     **Empty and sparse history.** The series begins at the first snapshot in the
     *     database, never earlier: points before any balance exists are omitted rather than
     *     reported as zero, because a chart starting at zero would show a fortune appearing
     *     overnight. An empty database returns no points, and a single snapshot returns a
     *     single point — both are normal states on day one, not errors.
     */
    get: operations["get_net_worth_series_net_worth_series_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/ready": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Ready
     * @description Readiness: the database is reachable.
     *
     *     Returns 503 rather than raising, so the body shape is the same either way and a
     *     caller can distinguish "unreachable" from "the API itself is broken".
     */
    get: operations["ready_ready_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rules": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List Rules */
    get: operations["list_rules_rules_get"];
    put?: never;
    /** Create Rule */
    post: operations["create_rule_rules_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rules/apply": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Apply Rules
     * @description Safe to re-run over all history. Never overwrites a manual category.
     */
    post: operations["apply_rules_rules_apply_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rules/preview": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Preview Rule
     * @description Which existing transactions a pattern would match, before it is saved.
     *
     *     Runs the engine's own matcher over the same subject text `apply` uses, rather than
     *     approximating it with a database `LIKE`. An approximation would agree with the
     *     engine right up until the pattern got subtle enough to actually need checking,
     *     which is the only time anyone looks.
     *
     *     Writes nothing, and saves nothing: this is the step between typing a regex and
     *     finding out it re-categorised two years of history.
     */
    post: operations["preview_rule_rules_preview_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/rules/{rule_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Rule */
    delete: operations["delete_rule_rules__rule_id__delete"];
    options?: never;
    head?: never;
    /** Update Rule */
    patch: operations["update_rule_rules__rule_id__patch"];
    trace?: never;
  };
  "/runway": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Runway
     * @description Months of runway from liquid assets, at 3/6/12-month trailing burn.
     *
     *     **Burn is gross spend excluding transfers; income is not netted.** This answers
     *     "how long if income stopped", which is the only version of the question worth a
     *     tile while income is still arriving.
     *
     *     **The current month is always excluded** from the averages. It is partial by
     *     definition, and averaging it in makes burn look artificially low every single
     *     month — always in the direction that overstates how long the money lasts.
     *
     *     **Months with no transaction data are skipped, not counted as zero.** Missing data
     *     is not a month you spent nothing, and treating it as one drags the average down.
     *     Months spending more than three times the window's median are excluded as
     *     outliers, so one house deposit does not triple the apparent burn — but only once
     *     there are at least three months, since with two the median is meaningless.
     *
     *     **Liquid assets only.** A house is not runway and neither is a 401k you would pay
     *     a penalty to reach.
     */
    get: operations["get_runway_runway_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/spend": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Spend
     * @description Spend for a period, defaulting to month-to-date.
     *
     *     **Transfers and income are excluded.** Moving money between your own accounts is
     *     not spending, and if it appears here every number on the dashboard loses
     *     credibility. `excluded_transfer_count` reports how many rows that removed, so the
     *     exclusion is visible rather than merely true.
     *
     *     **Uncategorised is a bucket, not a hole.** Rows with no category still count
     *     toward the total and appear under their own name — it is the prompt to add a rule,
     *     and dropping it would make the total quietly understate reality.
     *
     *     **No ownership adjustment.** A $60 grocery charge on a jointly-owned card is $60
     *     of spend, not $30. The groceries were bought once. This is the one figure in the
     *     app where ownership deliberately does not apply — see
     *     docs/ARCHITECTURE.md#users-and-ownership.
     */
    get: operations["get_spend_spend_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transactions": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List Transactions
     * @description Transactions, newest first, with filters and a total for pagination.
     *
     *     `uncategorised=true` is the filter the dashboard links to: uncategorised spend is
     *     surfaced prominently as a prompt to add a rule, and this is where that prompt
     *     leads.
     */
    get: operations["list_transactions_transactions_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transactions/bulk-categorise": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Categorise
     * @description Categorise many at once — the same manual write, applied to a selection.
     */
    post: operations["bulk_categorise_transactions_bulk_categorise_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transactions/bulk-transfer": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Bulk Transfer
     * @description Mark transactions as the two sides of one transfer, or unlink them.
     *
     *     A pair needs both sides, so linking fewer than two is rejected rather than
     *     quietly creating a group of one — a lone "transfer" that pairs with nothing is
     *     indistinguishable from a mistake, and it changes no total either way.
     *
     *     Unlinking accepts a single id, because breaking a bad pairing one side at a time
     *     is a reasonable thing to want.
     */
    post: operations["bulk_transfer_transactions_bulk_transfer_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/transactions/{transaction_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /**
     * Update Transaction
     * @description Set a category by hand.
     *
     *     Records `category_source='manual'`, which the rules engine treats as untouchable.
     *     That pairing is the whole reason the column exists: without it, the next rule run
     *     would quietly undo every correction a person made.
     */
    patch: operations["update_transaction_transactions__transaction_id__patch"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AccountCreate */
    AccountCreate: {
      /** Institution Id */
      institution_id?: number | null;
      /**
       * Institution Name
       * @description Create-or-reuse an institution by name.
       */
      institution_name?: string | null;
      kind: components["schemas"]["AccountKind"];
      /** Name */
      name: string;
      /** Opening Balance As Of */
      opening_balance_as_of?: string | null;
      /** Opening Balance Cents */
      opening_balance_cents?: number | null;
      /** Owner User Id */
      owner_user_id?: number | null;
      /** Ownership Percentage Bps */
      ownership_percentage_bps?: number | null;
      source?: components["schemas"]["DataSource"] | null;
      subtype: components["schemas"]["AccountSubtype"];
    };
    /** AccountDetail */
    AccountDetail: {
      /**
       * Adjusted Balance Cents
       * @description Balance after the viewer's ownership stake.
       */
      adjusted_balance_cents?: number | null;
      /** Balance As Of */
      balance_as_of?: string | null;
      /**
       * Balance Cents
       * @description Raw balance, unadjusted.
       */
      balance_cents?: number | null;
      /** Closed At */
      closed_at?: string | null;
      /** Currency */
      currency: string;
      /** Current Stake Bps */
      current_stake_bps?: number | null;
      /** Id */
      id: number;
      institution?: components["schemas"]["InstitutionRead"] | null;
      /**
       * Is Stale
       * @default false
       */
      is_stale: boolean;
      kind: components["schemas"]["AccountKind"];
      /** Name */
      name: string;
      source: components["schemas"]["DataSource"];
      /** Stakes */
      stakes: components["schemas"]["StakeRead"][];
      subtype: components["schemas"]["AccountSubtype"];
    };
    /**
     * AccountGroup
     * @description Accounts of one kind with their subtotals.
     */
    AccountGroup: {
      /** Accounts */
      accounts: components["schemas"]["AccountRead"][];
      /**
       * Adjusted Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      adjusted_total_cents: number;
      kind: components["schemas"]["AccountKind"];
      /**
       * Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      total_cents: number;
    };
    /** AccountHistory */
    AccountHistory: {
      /** Account Id */
      account_id: number;
      /** Points */
      points: components["schemas"]["BalanceRead"][];
    };
    /**
     * AccountKind
     * @description What a balance means for net worth.
     *
     *     Liabilities are stored as **positive** balances. Net worth subtracts them. Storing
     *     debt as a negative number makes every aggregate ambiguous — you can never tell
     *     whether a sum already accounted for the sign.
     * @enum {string}
     */
    AccountKind: "liquid_asset" | "illiquid_asset" | "liability";
    /** AccountList */
    AccountList: {
      /**
       * Adjusted Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      adjusted_total_cents: number;
      /** Groups */
      groups: components["schemas"]["AccountGroup"][];
      /**
       * Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      total_cents: number;
    };
    /**
     * AccountRead
     * @description An account with both raw and ownership-adjusted balances.
     *
     *     Both are exposed deliberately. A 50%-owned rental should visibly show the full
     *     value and your share — that distinction is the feature this app has and an
     *     off-the-shelf one does not.
     */
    AccountRead: {
      /**
       * Adjusted Balance Cents
       * @description Balance after the viewer's ownership stake.
       */
      adjusted_balance_cents?: number | null;
      /** Balance As Of */
      balance_as_of?: string | null;
      /**
       * Balance Cents
       * @description Raw balance, unadjusted.
       */
      balance_cents?: number | null;
      /** Closed At */
      closed_at?: string | null;
      /** Currency */
      currency: string;
      /** Current Stake Bps */
      current_stake_bps?: number | null;
      /** Id */
      id: number;
      institution?: components["schemas"]["InstitutionRead"] | null;
      /**
       * Is Stale
       * @default false
       */
      is_stale: boolean;
      kind: components["schemas"]["AccountKind"];
      /** Name */
      name: string;
      source: components["schemas"]["DataSource"];
      subtype: components["schemas"]["AccountSubtype"];
    };
    /**
     * AccountSubtype
     * @enum {string}
     */
    AccountSubtype:
      | "checking"
      | "savings"
      | "money_market"
      | "cd"
      | "brokerage"
      | "ira"
      | "roth_ira"
      | "401k"
      | "hsa"
      | "529"
      | "real_estate"
      | "vehicle"
      | "other_asset"
      | "credit_card"
      | "mortgage"
      | "auto_loan"
      | "student_loan"
      | "personal_loan"
      | "other_liability";
    /** AccountUpdate */
    AccountUpdate: {
      /** Closed At */
      closed_at?: string | null;
      /** Institution Id */
      institution_id?: number | null;
      /** Name */
      name?: string | null;
      subtype?: components["schemas"]["AccountSubtype"] | null;
    };
    /**
     * AuthenticationOptions
     * @description Server-generated options for `navigator.credentials.get()`.
     */
    AuthenticationOptions: {
      /** Challenge Id */
      challenge_id: string;
      /** Options */
      options: {
        [key: string]: unknown;
      };
    };
    /** AuthenticationVerify */
    AuthenticationVerify: {
      /** Challenge Id */
      challenge_id: string;
      /** Credential */
      credential: {
        [key: string]: unknown;
      };
    };
    /** BalanceCreate */
    BalanceCreate: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Balance Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      balance_cents: number;
      source?: components["schemas"]["DataSource"] | null;
    };
    /** BalanceRead */
    BalanceRead: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Balance Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      balance_cents: number;
      /**
       * Is Stale
       * @description True when carried forward from a snapshot older than 90 days.
       */
      is_stale: boolean;
      source: components["schemas"]["DataSource"];
    };
    /** Body_preview_csv_import_csv_preview_post */
    Body_preview_csv_import_csv_preview_post: {
      /** Account Id */
      account_id: number;
      /** File */
      file: string;
      /** Mapping */
      mapping?: string | null;
    };
    /** BulkCategorise */
    BulkCategorise: {
      /** Category Id */
      category_id?: number | null;
      /** Transaction Ids */
      transaction_ids: number[];
    };
    /** BulkCategoriseResult */
    BulkCategoriseResult: {
      /** Updated */
      updated: number;
    };
    /**
     * BulkTransfer
     * @description Link transactions as the two sides of one transfer, or unlink them.
     *
     *     `transfer_group_id` records the pairing only. What keeps a transfer out of the
     *     spend figures is its category's `kind`, not this field — see
     *     docs/ARCHITECTURE.md#transfers. Marking a pair here and leaving both sides
     *     categorised as expenses would link them and change no total.
     */
    BulkTransfer: {
      /**
       * Linked
       * @description False clears the group, leaving each transaction unpaired.
       * @default true
       */
      linked: boolean;
      /** Transaction Ids */
      transaction_ids: number[];
    };
    /** BulkTransferResult */
    BulkTransferResult: {
      /** Transfer Group Id */
      transfer_group_id?: string | null;
      /** Updated */
      updated: number;
    };
    /** BurnWindow */
    BurnWindow: {
      /**
       * Average Monthly Spend Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      average_monthly_spend_cents: number;
      /**
       * Months
       * @description Trailing window length: 3, 6, or 12.
       */
      months: number;
      /**
       * Months Of Runway
       * @description Null when average spend is zero.
       */
      months_of_runway?: number | null;
    };
    /** CategoryRead */
    CategoryRead: {
      /** Id */
      id: number;
      /** Kind */
      kind: string;
      /** Name */
      name: string;
      /** Parent Id */
      parent_id?: number | null;
    };
    /**
     * CategorySource
     * @description How a transaction got its category.
     *
     *     Rules never overwrite `manual`. Re-running the rule set over all history must be
     *     safe, and a human decision outranks a pattern match.
     * @enum {string}
     */
    CategorySource: "import" | "rule" | "manual";
    /**
     * ColumnMapping
     * @description Maps this file's headers onto transaction fields. Header names only, never values.
     */
    ColumnMapping: {
      /** Amount */
      amount: string;
      /** Description */
      description?: string | null;
      /** External Id */
      external_id?: string | null;
      /** Invert Amount */
      invert_amount?: boolean | null;
      /** Merchant */
      merchant?: string | null;
      /** Posted At */
      posted_at: string;
    };
    /**
     * DataSource
     * @description Where a row came from.
     *
     *     v1 implements `manual` and `csv` only. The aggregator values ship anyway so that
     *     adding a connector behind the SourceAdapter interface needs no migration.
     * @enum {string}
     */
    DataSource: "manual" | "csv" | "teller" | "plaid" | "simplefin";
    /**
     * ErrorDetail
     * @description One field-level problem.
     */
    ErrorDetail: {
      /** Code */
      code?: string | null;
      /**
       * Field
       * @description Dotted path, e.g. `body.amount_cents`.
       */
      field?: string | null;
      /** Message */
      message: string;
    };
    /**
     * ErrorResponse
     * @description The single error shape for every non-2xx response.
     *
     *     Defined once and reused so the frontend writes one error handler rather than one
     *     per endpoint, and so a new route cannot invent its own shape.
     */
    ErrorResponse: {
      /** Detail */
      detail: string;
      /** Errors */
      errors?: components["schemas"]["ErrorDetail"][];
    };
    /** ExportMeta */
    ExportMeta: {
      /** Account Count */
      account_count: number;
      /**
       * Generated At
       * Format: date-time
       */
      generated_at: string;
      /** Snapshot Count */
      snapshot_count: number;
      /** Transaction Count */
      transaction_count: number;
    };
    /** ExportRead */
    ExportRead: {
      /** Accounts */
      accounts: {
        [key: string]: unknown;
      }[];
      /** Balance Snapshots */
      balance_snapshots: {
        [key: string]: unknown;
      }[];
      /** Categories */
      categories: {
        [key: string]: unknown;
      }[];
      /** Categorization Rules */
      categorization_rules: {
        [key: string]: unknown;
      }[];
      meta: components["schemas"]["ExportMeta"];
      /** Ownership Stakes */
      ownership_stakes: {
        [key: string]: unknown;
      }[];
      /** Transactions */
      transactions: {
        [key: string]: unknown;
      }[];
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** HealthResponse */
    HealthResponse: {
      /**
       * Status
       * @constant
       */
      status: "ok";
    };
    /** ImportCommitRequest */
    ImportCommitRequest: {
      /** Account Id */
      account_id: number;
      /**
       * Content
       * @description Raw CSV text.
       */
      content: string;
      mapping: components["schemas"]["ColumnMapping"];
      /**
       * Save Mapping As
       * @description Persist this mapping against the account for reuse.
       */
      save_mapping_as?: string | null;
    };
    /**
     * ImportPreview
     * @description A dry run. Shows what *would* change, per row.
     *
     *     The preview is the safety net for importing real exports — build it first, not as
     *     a later nicety.
     */
    ImportPreview: {
      /** Account Id */
      account_id: number;
      /** @description The mapping this dry run actually used, whatever its origin. */
      detected_mapping: components["schemas"]["ColumnMapping"];
      /** Errors */
      errors?: string[];
      /**
       * Mapping Source
       * @description supplied | saved | detected. Lets the wizard say a mapping was remembered rather than presenting a guess and a memory as the same thing.
       * @default detected
       */
      mapping_source: string;
      /** Rows */
      rows: components["schemas"]["PreviewRow"][];
      /** Will Create */
      will_create: number;
      /** Will Skip */
      will_skip: number;
      /** Will Update */
      will_update: number;
    };
    /** ImportResult */
    ImportResult: {
      /** Created */
      created: number;
      /** Errors */
      errors?: string[];
      /** Skipped */
      skipped: number;
      /** Updated */
      updated: number;
    };
    /** InstitutionRead */
    InstitutionRead: {
      /** Id */
      id: number;
      /** Name */
      name: string;
    };
    /**
     * Interval
     * @enum {string}
     */
    Interval: "day" | "week" | "month";
    /** KindBreakdown */
    KindBreakdown: {
      kind: components["schemas"]["AccountKind"];
      /**
       * Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      total_cents: number;
    };
    /**
     * MatchType
     * @enum {string}
     */
    MatchType: "contains" | "equals" | "starts_with" | "regex";
    /** NetWorthPoint */
    NetWorthPoint: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Assets Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      assets_cents: number;
      /**
       * Liabilities Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      liabilities_cents: number;
      /**
       * Net Worth Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      net_worth_cents: number;
      /**
       * Stale Account Count
       * @description Accounts at this point using a balance carried forward past 90 days.
       */
      stale_account_count: number;
    };
    /** NetWorthRead */
    NetWorthRead: {
      /**
       * As Of
       * Format: date
       */
      as_of: string;
      /**
       * Assets Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      assets_cents: number;
      /** Breakdown */
      breakdown: components["schemas"]["KindBreakdown"][];
      /**
       * Liabilities Cents
       * @description Positive. Net worth subtracts this — liabilities are stored positive.
       */
      liabilities_cents: number;
      /**
       * Net Worth Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      net_worth_cents: number;
      /**
       * Stale Account Ids
       * @description Accounts contributing a balance carried forward more than 90 days.
       */
      stale_account_ids: number[];
      view: components["schemas"]["ViewScope"];
    };
    /**
     * NetWorthSeries
     * @description A time series where each point uses that date's balances and that date's stakes.
     *
     *     Not today's stakes applied to old balances — that would make a stake change
     *     retroactively rewrite the chart.
     */
    NetWorthSeries: {
      /** Interval */
      interval: string;
      /** Points */
      points: components["schemas"]["NetWorthPoint"][];
      view: components["schemas"]["ViewScope"];
    };
    /**
     * Page
     * @description Pagination envelope metadata.
     */
    Page: {
      /** Limit */
      limit: number;
      /** Offset */
      offset: number;
      /** Total */
      total: number;
    };
    /** PreviewRow */
    PreviewRow: {
      /**
       * Action
       * @description create | update | skip
       */
      action: string;
      /** Amount Cents */
      amount_cents?: number | null;
      /** Description */
      description?: string | null;
      /** Errors */
      errors?: string[];
      /** External Id */
      external_id?: string | null;
      /** Merchant */
      merchant?: string | null;
      /** Posted At */
      posted_at?: string | null;
      /** Row Number */
      row_number: number;
    };
    /** ReadyResponse */
    ReadyResponse: {
      /** Database */
      database: boolean;
      /**
       * Status
       * @enum {string}
       */
      status: "ok" | "unavailable";
    };
    /**
     * RegistrationOptions
     * @description Server-generated options for `navigator.credentials.create()`.
     */
    RegistrationOptions: {
      /** Challenge Id */
      challenge_id: string;
      /** Options */
      options: {
        [key: string]: unknown;
      };
    };
    /** RegistrationVerify */
    RegistrationVerify: {
      /** Challenge Id */
      challenge_id: string;
      /** Credential */
      credential: {
        [key: string]: unknown;
      };
    };
    /** RuleApplyRequest */
    RuleApplyRequest: {
      /**
       * Only Uncategorised
       * @description Re-running over all history is safe either way — manual categories are never overwritten.
       */
      only_uncategorised?: boolean | null;
    };
    /** RuleApplyResult */
    RuleApplyResult: {
      /** Categorised */
      categorised: number;
      /** Examined */
      examined: number;
      /** Manual Preserved */
      manual_preserved: number;
    };
    /** RuleCreate */
    RuleCreate: {
      /** Category Id */
      category_id: number;
      match_type?: components["schemas"]["MatchType"] | null;
      /** Pattern */
      pattern: string;
      /** Priority */
      priority?: number | null;
    };
    /**
     * RulePreviewRequest
     * @description A pattern to try before saving it.
     */
    RulePreviewRequest: {
      /**
       * Limit
       * @default 20
       */
      limit: number;
      match_type?: components["schemas"]["MatchType"] | null;
      /** Pattern */
      pattern: string;
    };
    /**
     * RulePreviewResult
     * @description What a pattern would hit, run through the engine's own matcher.
     *
     *     Computing this with a second implementation — a `LIKE` query, say — would produce a
     *     preview that agrees with the engine until it doesn't, which is worse than no
     *     preview: it is a safety net that fails silently in exactly the cases a regex is
     *     subtle enough to need one.
     *
     *     `already_manual` counts matches the engine would leave alone because a human
     *     already categorised them. It is what stops the count reading as a promise the run
     *     will not keep.
     */
    RulePreviewResult: {
      /** Already Manual */
      already_manual: number;
      /** Match Count */
      match_count: number;
      /** Matches */
      matches: components["schemas"]["TransactionRead"][];
    };
    /** RuleRead */
    RuleRead: {
      /** Category Id */
      category_id: number;
      /** Category Name */
      category_name: string;
      /** Id */
      id: number;
      match_type: components["schemas"]["MatchType"];
      /** Pattern */
      pattern: string;
      /**
       * Priority
       * @description Lower runs first. First match wins.
       */
      priority: number;
    };
    /** RuleUpdate */
    RuleUpdate: {
      /** Category Id */
      category_id?: number | null;
      match_type?: components["schemas"]["MatchType"] | null;
      /** Pattern */
      pattern?: string | null;
      /** Priority */
      priority?: number | null;
    };
    /**
     * RunwayRead
     * @description Gross spend, excluding transfers. Income is not netted off.
     *
     *     Gross answers "how long if income stopped", which is the question runway is for.
     *     Netting income in would make the number meaningless while employed.
     */
    RunwayRead: {
      /**
       * Liquid Assets Cents
       * @description Ownership-adjusted, kind='liquid_asset' only.
       */
      liquid_assets_cents: number;
      /**
       * Partial Month Excluded
       * @description True when the current, incomplete month was left out. Averaging it in makes burn look artificially low every month.
       */
      partial_month_excluded: boolean;
      /** Windows */
      windows: components["schemas"]["BurnWindow"][];
    };
    /** SessionRead */
    SessionRead: {
      /** Display Name */
      display_name: string;
      /** Email */
      email: string;
      /** User Id */
      user_id: number;
    };
    /** SpendBucket */
    SpendBucket: {
      /**
       * Category Id
       * @description Null is the explicit uncategorised bucket.
       */
      category_id?: number | null;
      /** Category Name */
      category_name: string;
      /** Change Cents */
      change_cents?: number | null;
      /**
       * Parent Id
       * @description The bucket's parent category under `group_by=category`. Always null under `group_by=parent_category`. Lets a client drill from a parent to its children without a separate category-tree request.
       */
      parent_id?: number | null;
      /** Prior Period Cents */
      prior_period_cents?: number | null;
      /**
       * Spend Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      spend_cents: number;
    };
    /**
     * SpendGrouping
     * @enum {string}
     */
    SpendGrouping: "category" | "parent_category";
    /**
     * SpendRead
     * @description Spend for a period.
     *
     *     Transfers are excluded — moving money between your own accounts is not spending,
     *     and if it appears as spending every number on the dashboard loses credibility.
     *     Uncategorised is returned as its own bucket rather than dropped: it is the prompt
     *     to add a rule, not noise to hide.
     */
    SpendRead: {
      /** Buckets */
      buckets: components["schemas"]["SpendBucket"][];
      /**
       * End
       * Format: date
       */
      end: string;
      /**
       * Excluded Transfer Count
       * @default 0
       */
      excluded_transfer_count: number;
      group_by: components["schemas"]["SpendGrouping"];
      /**
       * Start
       * Format: date
       */
      start: string;
      /**
       * Total Cents
       * @description Amount in integer cents. 1234 means $12.34.
       */
      total_cents: number;
    };
    /** StakeCreate */
    StakeCreate: {
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /** Owner User Id */
      owner_user_id: number;
      /**
       * Percentage Bps
       * @description Basis points. 5000 means 50.00%.
       */
      percentage_bps: number;
    };
    /**
     * StakeRead
     * @description A stake with its effective dates.
     *
     *     The dates are exposed rather than just the current percentage: showing them is
     *     what makes effective-dating visible as a feature instead of hidden plumbing, and
     *     it is how a stake entered against the wrong date gets caught.
     */
    StakeRead: {
      /**
       * Effective From
       * Format: date
       */
      effective_from: string;
      /** Effective To */
      effective_to?: string | null;
      /** Id */
      id: number;
      /** Owner Display Name */
      owner_display_name: string;
      /** Owner User Id */
      owner_user_id: number;
      /**
       * Percentage Bps
       * @description Basis points. 5000 means 50.00%.
       */
      percentage_bps: number;
    };
    /** TransactionList */
    TransactionList: {
      /** Items */
      items: components["schemas"]["TransactionRead"][];
      page: components["schemas"]["Page"];
    };
    /** TransactionRead */
    TransactionRead: {
      /** Account Id */
      account_id: number;
      /** Account Name */
      account_name: string;
      /**
       * Amount Cents
       * @description Signed: outflows negative, inflows positive.
       */
      amount_cents: number;
      category?: components["schemas"]["CategoryRead"] | null;
      category_source?: components["schemas"]["CategorySource"] | null;
      /** Description */
      description?: string | null;
      /** Id */
      id: number;
      /** Merchant */
      merchant?: string | null;
      /**
       * Posted At
       * Format: date
       */
      posted_at: string;
      /** Transfer Group Id */
      transfer_group_id?: string | null;
    };
    /**
     * TransactionUpdate
     * @description Manual re-categorisation.
     *
     *     Setting a category here records ``category_source='manual'``, and re-running the
     *     rules engine never overwrites it. That protection is the whole reason
     *     ``category_source`` exists.
     */
    TransactionUpdate: {
      /** Category Id */
      category_id?: number | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Context */
      ctx?: Record<string, never>;
      /** Input */
      input?: unknown;
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
    };
    /**
     * ViewScope
     * @description Whose money a figure describes.
     *
     *     `mine` applies the viewer's ownership stake; `household` sums every stake. The
     *     only multi-user surface in the app — see ARCHITECTURE#users-and-ownership.
     * @enum {string}
     */
    ViewScope: "mine" | "household";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  list_all_accounts_get: {
    parameters: {
      query?: {
        view?: components["schemas"]["ViewScope"];
        include_closed?: boolean;
        as_of?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountList"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_accounts_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  detail_accounts__account_id__get: {
    parameters: {
      query?: {
        view?: components["schemas"]["ViewScope"];
      };
      header?: never;
      path: {
        account_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountDetail"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_accounts__account_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AccountUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  add_balance_accounts__account_id__balances_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BalanceCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BalanceRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  history_accounts__account_id__history_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AccountHistory"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  set_stake_accounts__account_id__stakes_post: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        account_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["StakeCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["StakeRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authentication_options_auth_login_options_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AuthenticationOptions"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  authentication_verify_auth_login_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["AuthenticationVerify"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionRead"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  registration_options_auth_register_options_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RegistrationOptions"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  registration_verify_auth_register_verify_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RegistrationVerify"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionRead"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  read_session_auth_session_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SessionRead"];
        };
      };
      /** @description Unauthorized */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_categories_categories_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CategoryRead"][];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_export_export_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ExportRead"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  health_health_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HealthResponse"];
        };
      };
    };
  };
  commit_csv_import_csv_commit_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ImportCommitRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportResult"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  preview_csv_import_csv_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_preview_csv_import_csv_preview_post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ImportPreview"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_net_worth_net_worth_get: {
    parameters: {
      query?: {
        as_of?: string | null;
        view?: components["schemas"]["ViewScope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NetWorthRead"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_net_worth_series_net_worth_series_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        interval?: components["schemas"]["Interval"];
        view?: components["schemas"]["ViewScope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["NetWorthSeries"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  ready_ready_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
      /** @description Service Unavailable */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ReadyResponse"];
        };
      };
    };
  };
  list_rules_rules_get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleRead"][];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  create_rule_rules_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  apply_rules_rules_apply_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleApplyRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleApplyResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  preview_rule_rules_preview_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RulePreviewRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RulePreviewResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  delete_rule_rules__rule_id__delete: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rule_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_rule_rules__rule_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        rule_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RuleRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_runway_runway_get: {
    parameters: {
      query?: {
        view?: components["schemas"]["ViewScope"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["RunwayRead"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  get_spend_spend_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        group_by?: components["schemas"]["SpendGrouping"];
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["SpendRead"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  list_transactions_transactions_get: {
    parameters: {
      query?: {
        from?: string | null;
        to?: string | null;
        account_id?: number | null;
        category_id?: number | null;
        uncategorised?: boolean | null;
        search?: string | null;
        limit?: number;
        offset?: number;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransactionList"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  bulk_categorise_transactions_bulk_categorise_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkCategorise"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkCategoriseResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  bulk_transfer_transactions_bulk_transfer_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkTransfer"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BulkTransferResult"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
  update_transaction_transactions__transaction_id__patch: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        transaction_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TransactionUpdate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TransactionRead"];
        };
      };
      /** @description Not Found */
      404: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
      /** @description Unprocessable Entity */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ErrorResponse"];
        };
      };
    };
  };
}
