"""Generate the reference docs that must never be hand-kept.

Two files under ``docs/generated/``, both derived from the code:

- ``db-schema.md`` from the SQLAlchemy metadata — every table, column, constraint and index.
- ``api-endpoints.md`` from the OpenAPI schema FastAPI builds — every operation, its
  parameters, request and response models, and every schema's fields.

``make docs`` writes them; ``make docs-check`` runs ``--check``, which fails if what is
committed differs from what would be generated. The same pattern as ``make types`` and
``make types-check``, for the same reason: a hand-maintained copy of something the code
already knows goes stale, and a stale reference is worse than none because it is trusted.

Needs no database. The metadata is the models; the OpenAPI schema is built from the
Pydantic models alone (see ``export_openapi.py``).

Why the tables are generated from the metadata rather than a migrated database: the
metadata is what the code believes, and ``tests/test_schema.py`` already holds the
migrations to it.
"""

from __future__ import annotations

import argparse
import difflib
import enum
import sys
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from sqlalchemy import CheckConstraint, Column, Enum, ForeignKeyConstraint, Table, UniqueConstraint
from sqlalchemy.dialects import postgresql
from sqlalchemy.sql.schema import MetaData

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUT = REPO_ROOT / "docs" / "generated"

SCHEMA_FILE = "db-schema.md"
ENDPOINTS_FILE = "api-endpoints.md"

HTTP_METHODS = ("get", "post", "put", "patch", "delete")

DIALECT = postgresql.dialect()  # type: ignore[no-untyped-call]


def _header(title: str, source: str) -> list[str]:
    return [
        f"# {title}",
        "",
        f"<!-- Generated by `make docs` from {source}. Do not edit: change the code and run "
        "`make docs`; `make docs-check` fails on drift. -->",
        "",
        f"Generated from {source}. The *why* lives in "
        "[design-docs/](../design-docs/index.md); this file is only the *what*.",
        "",
    ]


def _cell(text: str) -> str:
    """Make a value safe inside a markdown table cell."""
    return text.replace("|", "\\|").replace("\n", " ").strip()


def _first_paragraph(doc: str | None) -> str:
    if not doc:
        return ""
    paragraph: list[str] = []
    for line in doc.strip().splitlines():
        if not line.strip():
            break
        paragraph.append(line.strip())
    return " ".join(paragraph)


# ── db-schema.md ──────────────────────────────────────────────────────────────


def _column_type(column: Column[Any]) -> str:
    rendered = str(column.type.compile(dialect=DIALECT))
    if isinstance(column.type, Enum) and column.type.enums:
        rendered += " (" + " | ".join(column.type.enums) + ")"
    return rendered


def _column_default(column: Column[Any]) -> str:
    if column.server_default is not None:
        arg = getattr(column.server_default, "arg", None)
        text = getattr(arg, "text", arg)
        return f"server: `{text}`"
    if column.default is not None:
        arg = getattr(column.default, "arg", None)
        if callable(arg):
            return "python: callable"
        if isinstance(arg, enum.Enum):
            arg = arg.value
        return f"python: `{arg!r}`"
    return ""


def _column_keys(column: Column[Any]) -> str:
    keys: list[str] = []
    if column.primary_key:
        keys.append("PK")
    for fk in sorted(column.foreign_keys, key=lambda fk: fk.target_fullname):
        on_delete = f" ON DELETE {fk.ondelete}" if fk.ondelete else ""
        keys.append(f"FK → `{fk.target_fullname}`{on_delete}")
    if column.unique:
        keys.append("unique")
    return ", ".join(keys)


def _table_docstrings(metadata: MetaData) -> dict[str, str]:
    """First paragraph of each mapped class's docstring, keyed by table name."""
    from app.db import Base

    docs: dict[str, str] = {}
    for mapper in Base.registry.mappers:
        table = getattr(mapper.class_, "__table__", None)
        if isinstance(table, Table) and table.metadata is metadata:
            docs[table.name] = _first_paragraph(mapper.class_.__doc__)
    return docs


def _constraints(table: Table) -> list[str]:
    lines: list[str] = []
    named = sorted(
        (c for c in table.constraints if isinstance(c, CheckConstraint | UniqueConstraint)),
        key=lambda c: str(c.name or ""),
    )
    for constraint in named:
        if isinstance(constraint, CheckConstraint):
            lines.append(f"- CHECK `{constraint.name}`: `{constraint.sqltext}`")
        else:
            columns = ", ".join(c.name for c in constraint.columns)
            lines.append(f"- UNIQUE `{constraint.name}`: ({columns})")
    composite_fks = sorted(
        (
            c
            for c in table.constraints
            if isinstance(c, ForeignKeyConstraint) and len(c.columns) > 1
        ),
        key=lambda c: str(c.name or ""),
    )
    for fk in composite_fks:
        columns = ", ".join(c.name for c in fk.columns)
        lines.append(f"- FOREIGN KEY `{fk.name}`: ({columns}) → `{fk.referred_table.name}`")
    for index in sorted(table.indexes, key=lambda i: str(i.name)):
        columns = ", ".join(
            getattr(expression, "name", str(expression)) for expression in index.expressions
        )
        flags = " unique" if index.unique else ""
        where = index.dialect_options["postgresql"].get("where")
        partial = f" where `{where}`" if where is not None else ""
        lines.append(f"- INDEX `{index.name}`{flags}: ({columns}){partial}")
    return lines


def render_db_schema(metadata: MetaData | None = None) -> str:
    if metadata is None:
        import app.models  # noqa: F401 — registers every model on the metadata
        from app.db import Base

        metadata = Base.metadata

    docs = _table_docstrings(metadata)
    tables = sorted(metadata.tables.values(), key=lambda t: t.name)
    out = _header("Database schema", "the SQLAlchemy models in `api/app/models/`")
    out.append(
        f"{len(tables)} tables. Money columns are `NUMERIC(19, 2)`; see "
        "[ownership-and-rounding](../design-docs/ownership-and-rounding.md#money)."
    )
    out.append("")
    out.append(" · ".join(f"[`{t.name}`](#{t.name})" for t in tables))
    out.append("")
    for table in tables:
        out.append(f"## {table.name}")
        out.append("")
        if docs.get(table.name):
            out.append(_cell(docs[table.name]))
            out.append("")
        out.append("| Column | Type | Null | Default | Keys |")
        out.append("|---|---|---|---|---|")
        for column in table.columns:
            out.append(
                f"| `{column.name}` | {_cell(_column_type(column))} | "
                f"{'yes' if column.nullable else 'no'} | {_cell(_column_default(column))} | "
                f"{_cell(_column_keys(column))} |"
            )
        out.append("")
        constraints = _constraints(table)
        if constraints:
            out.extend(constraints)
            out.append("")
    return "\n".join(out).rstrip() + "\n"


# ── api-endpoints.md ──────────────────────────────────────────────────────────


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _schema_type(schema: dict[str, Any]) -> str:
    """A compact, readable type for a JSON schema fragment."""
    if "$ref" in schema:
        return _ref_name(schema["$ref"])
    if "anyOf" in schema:
        return " | ".join(_schema_type(part) for part in schema["anyOf"])
    if "allOf" in schema and len(schema["allOf"]) == 1:
        return _schema_type(schema["allOf"][0])
    kind = schema.get("type")
    if kind == "array":
        return f"list[{_schema_type(schema.get('items', {}))}]"
    if "enum" in schema:
        return " | ".join(f"`{value}`" for value in schema["enum"])
    if kind == "string" and schema.get("format"):
        return f"string ({schema['format']})"
    if kind == "object" and "additionalProperties" in schema:
        values = schema["additionalProperties"]
        # JSON Schema allows `true` here, meaning "any value".
        inner = _schema_type(values) if isinstance(values, dict) else "any"
        return f"dict[str, {inner}]"
    return str(kind or "any")


def _parameters(operation: dict[str, Any]) -> str:
    parts: list[str] = []
    for parameter in operation.get("parameters", []):
        marker = "" if parameter.get("required") else "?"
        where = parameter.get("in", "")
        prefix = "{" + parameter["name"] + "}" if where == "path" else parameter["name"]
        parts.append(f"`{prefix}{marker}`: {_schema_type(parameter.get('schema', {}))}")
    return "<br>".join(parts)


def _request_body(operation: dict[str, Any]) -> str:
    body = operation.get("requestBody")
    if not body:
        return ""
    for media_type, content in sorted(body.get("content", {}).items()):
        schema = content.get("schema", {})
        label = _schema_type(schema)
        if media_type != "application/json":
            label = f"{media_type}: {label}"
        return label
    return ""


def _responses(operation: dict[str, Any]) -> tuple[str, str]:
    success = ""
    errors: list[str] = []
    for code, response in sorted(operation.get("responses", {}).items()):
        if code.startswith("2"):
            content = response.get("content", {}).get("application/json", {})
            shape = _schema_type(content["schema"]) if "schema" in content else "no body"
            success = f"{code} {shape}"
        else:
            errors.append(code)
    return success, ", ".join(errors)


def render_api_endpoints(openapi: dict[str, Any] | None = None) -> str:
    if openapi is None:
        # The same call `export_openapi.build_schema` makes, and what `make types` consumes.
        from app.main import app

        openapi = app.openapi()

    paths: dict[str, dict[str, Any]] = openapi.get("paths", {})
    out = _header("API endpoints", "the OpenAPI schema FastAPI builds from `api/app/`")
    out.append(
        "Every operation, from `app.openapi()`. The ticket that landed each route is in the "
        "hand-kept table at [api-contract.md#endpoints](../design-docs/api-contract.md#endpoints); "
        "the TypeScript types are `web/src/lib/api-types.ts`. Money is integer cents "
        "(`*_cents`), percentages integer basis points (`*_bps`)."
    )
    out.append("")
    out.append("## Operations")
    out.append("")
    out.append("| Method | Path | Summary | Parameters | Request body | Success | Errors |")
    out.append("|---|---|---|---|---|---|---|")
    count = 0
    for path in sorted(paths):
        for method in HTTP_METHODS:
            operation = paths[path].get(method)
            if operation is None:
                continue
            count += 1
            success, errors = _responses(operation)
            cells = [
                method.upper(),
                f"`{path}`",
                operation.get("summary", ""),
                _parameters(operation),
                _request_body(operation),
                success,
                errors,
            ]
            out.append("| " + " | ".join(_cell(cell) for cell in cells) + " |")
    out.append("")
    out.append(f"{count} operations on {len(paths)} paths.")
    out.append("")

    schemas: dict[str, dict[str, Any]] = openapi.get("components", {}).get("schemas", {})
    out.append("## Schemas")
    out.append("")
    out.append("Fields marked `?` are optional in the contract.")
    out.append("")
    for name in sorted(schemas):
        schema = schemas[name]
        properties: dict[str, Any] = schema.get("properties", {})
        if "enum" in schema:
            out.append(f"- **{name}** — enum: " + _schema_type(schema))
            continue
        required = set(schema.get("required", []))
        fields = ", ".join(
            f"`{field}{'' if field in required else '?'}`: {_schema_type(spec)}"
            for field, spec in properties.items()
        )
        out.append(f"- **{name}** — {fields}" if fields else f"- **{name}**")
    return "\n".join(out).rstrip() + "\n"


# ── write / check ─────────────────────────────────────────────────────────────


def render_all() -> dict[str, str]:
    return {SCHEMA_FILE: render_db_schema(), ENDPOINTS_FILE: render_api_endpoints()}


def write(out_dir: Path = DEFAULT_OUT, rendered: dict[str, str] | None = None) -> list[Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for name, text in (rendered or render_all()).items():
        path = out_dir / name
        path.write_text(text, encoding="utf-8")
        written.append(path)
    return written


def check(out_dir: Path = DEFAULT_OUT, rendered: dict[str, str] | None = None) -> list[str]:
    """Every generated file that is missing or differs, with a short diff and the fix."""
    problems: list[str] = []
    for name, expected in (rendered or render_all()).items():
        path = out_dir / name
        if not path.exists():
            problems.append(f"docs/generated/{name} is missing.")
            continue
        actual = path.read_text(encoding="utf-8")
        if actual != expected:
            diff = list(
                difflib.unified_diff(
                    actual.splitlines(),
                    expected.splitlines(),
                    f"committed {name}",
                    f"generated {name}",
                    lineterm="",
                    n=0,
                )
            )
            shown = "\n".join(f"    {line}" for line in diff[:12])
            more = f"\n    … {len(diff) - 12} more diff lines" if len(diff) > 12 else ""
            problems.append(f"docs/generated/{name} is out of date:\n{shown}{more}")
    return problems


FIX = (
    "Rule: docs/generated/ is derived from the code and never hand-edited (AGENTS.md).\n"
    "Fix: run `make docs` and commit the regenerated files with the change that caused them.\n"
    "If you edited a file in docs/generated/ by hand, revert it and change the models or\n"
    "routes instead."
)


def _report(problems: Iterable[str]) -> int:
    problems = list(problems)
    if not problems:
        print("generated docs are in sync")
        return 0
    print("", file=sys.stderr)
    for problem in problems:
        print(f"  {problem}", file=sys.stderr)
    print("", file=sys.stderr)
    print(FIX, file=sys.stderr)
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail on drift instead of writing")
    parser.add_argument("--out", type=Path, default=DEFAULT_OUT, help="output directory")
    args = parser.parse_args()
    if args.check:
        return _report(check(args.out))
    for path in write(args.out):
        print(f"wrote {path.relative_to(REPO_ROOT) if path.is_relative_to(REPO_ROOT) else path}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
