import { render, screen, waitFor } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { beforeEach, describe, expect, it, vi } from "vitest";

import { AdvisorScreen } from "@/app/(dashboard)/advisor/page";
import { monthName } from "@/components/advisor/review-offer";
import { takeQuestion } from "@/lib/advisor";
import { mockAdvisor } from "@/test/msw";

const push = vi.fn();
vi.mock("next/navigation", () => ({
  useRouter: () => ({ push }),
  usePathname: () => "/advisor",
}));

const AUGUST = { month: "2026-08-01", estimated_cost_cents: 22 };

beforeEach(() => {
  push.mockReset();
  localStorage.clear();
  sessionStorage.clear();
});

async function screenLoaded() {
  render(<AdvisorScreen />);
  await screen.findByRole("list", { name: "Conversations" });
}

describe("the monthly review offer", () => {
  it("names the month just ended and about what it costs", async () => {
    mockAdvisor({ status: { review_offer: AUGUST } });

    await screenLoaded();

    const offer = screen.getByRole("region", { name: "Review August" });
    expect(offer).toHaveTextContent("About $0.22");
    expect(screen.getByRole("button", { name: "Review August" })).toBeEnabled();
  });

  it("is not shown when the server offers nothing", async () => {
    mockAdvisor({ status: { review_offer: null } });

    await screenLoaded();

    expect(screen.queryByRole("region", { name: /^Review / })).not.toBeInTheDocument();
  });

  it("is free on the local model", async () => {
    mockAdvisor({ status: { review_offer: { ...AUGUST, estimated_cost_cents: null } } });

    await screenLoaded();

    expect(screen.getByRole("region", { name: "Review August" })).toHaveTextContent(
      "Free on the local model",
    );
  });

  it("starts a review only when taken, and carries its question without the URL", async () => {
    const calls = mockAdvisor({ status: { review_offer: AUGUST } });
    await screenLoaded();
    expect(calls.created).toEqual([]); // nothing generated by showing the offer

    await userEvent.click(screen.getByRole("button", { name: "Review August" }));

    await waitFor(() => expect(push).toHaveBeenCalled());
    expect(calls.created).toEqual([{ view: "mine", kind: "review" }]);
    const target = push.mock.calls[0][0] as string;
    expect(target).toBe("/advisor/7d0c9f5e-0000-4000-8000-0000000000ff");
    expect(takeQuestion("7d0c9f5e-0000-4000-8000-0000000000ff")).toBe("Review August.");
  });

  it("stays away for the month once put off, and returns for the next", async () => {
    mockAdvisor({ status: { review_offer: AUGUST } });
    const { unmount } = render(<AdvisorScreen />);
    await screen.findByRole("region", { name: "Review August" });

    await userEvent.click(screen.getByRole("button", { name: "Not now" }));

    expect(screen.queryByRole("region", { name: "Review August" })).not.toBeInTheDocument();
    unmount();
    render(<AdvisorScreen />);
    await screen.findByRole("list", { name: "Conversations" });
    expect(screen.queryByRole("region", { name: "Review August" })).not.toBeInTheDocument();
  });

  it("offers September after August was put off", async () => {
    localStorage.setItem("pfa:review-offer-dismissed", "2026-08-01");
    mockAdvisor({ status: { review_offer: { ...AUGUST, month: "2026-09-01" } } });

    await screenLoaded();

    expect(screen.getByRole("region", { name: "Review September" })).toBeInTheDocument();
  });

  it("names months in UTC, whatever the reader's time zone", () => {
    expect(monthName("2026-12-01")).toBe("December");
    expect(monthName("2027-01-01")).toBe("January");
  });
});
