import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

// Messages are written for whoever reads CI output: the rule, where it is documented, and
// how to fix the code. See docs/FRONTEND.md#layers.

const FETCH_MESSAGE =
  "Rule: the browser has one fetcher. Only src/lib/api.ts and the proxy route " +
  "src/app/api/[...path]/route.ts may call fetch(). Fix: use apiFetch() from @/lib/api, " +
  "which types the route and its response from the contract. Doc: docs/FRONTEND.md#layers.";

const API_TYPES_MESSAGE =
  "Rule: api-types.ts is generated by `make types` and has no runtime exports, so it may " +
  "only be imported as types. Fix: write `import type { … }`. Never hand-edit the file; " +
  "change the Pydantic model and run `make types`. Doc: docs/FRONTEND.md#layers.";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
  ]),
  {
    // The browser talks only to this origin, through one typed client. A stray fetch() is
    // how an absolute API URL, an untyped response, or a second error path gets in.
    name: "pfa/one-fetcher",
    files: ["**/*.{ts,tsx,js,mjs}"],
    // Brackets are escaped: unescaped, minimatch reads `[...path]` as a character class.
    ignores: ["src/lib/api.ts", "src/app/api/\\[...path\\]/route.ts"],
    rules: {
      "no-restricted-globals": ["error", { name: "fetch", message: FETCH_MESSAGE }],
      "no-restricted-properties": [
        "error",
        { object: "window", property: "fetch", message: FETCH_MESSAGE },
        { object: "globalThis", property: "fetch", message: FETCH_MESSAGE },
        { object: "self", property: "fetch", message: FETCH_MESSAGE },
      ],
    },
  },
  {
    // Generated from the Pydantic models; a value import would either fail at runtime or
    // tempt someone to add runtime code to a generated file.
    name: "pfa/generated-contract",
    files: ["**/*.{ts,tsx}"],
    rules: {
      "@typescript-eslint/no-restricted-imports": [
        "error",
        {
          paths: [{ name: "@/lib/api-types", allowTypeImports: true, message: API_TYPES_MESSAGE }],
          patterns: [
            {
              group: ["**/api-types", "./api-types"],
              allowTypeImports: true,
              message: API_TYPES_MESSAGE,
            },
          ],
        },
      ],
    },
  },
]);

export default eslintConfig;
